package org.smartjq.mvc.common.model;

import org.smartjq.mvc.common.model.base.BaseChatHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatHistory extends BaseChatHistory<ChatHistory> {
	public static final ChatHistory dao = new ChatHistory();
}
