package org.smartjq.mvc.common.model;

import org.smartjq.mvc.common.model.base.BaseCmsContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CmsContent extends BaseCmsContent<CmsContent> {
	public static final CmsContent dao = new CmsContent();
	
}
