package org.smartjq.mvc.common.model;

import java.util.List;

import org.smartjq.mvc.common.model.base.BaseDjNoticeUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DjNoticeUser extends BaseDjNoticeUser<DjNoticeUser> {
	public static final DjNoticeUser dao = new DjNoticeUser();
	public static String tableName = "dj_notice_user";
	
	/***
	 * 查询所有被通知人
	 * @param id
	 * @return
	 */
	public List<DjNoticeUser> getNoticeUserListByNoticeId(String id){
		return DjNoticeUser.dao.find("select * from dj_notice_user where notice_id = '"+id+"'");
	}
	
	public DjNoticeUser getNoticeUserByNoticeIdAndUserid(String id,String userid){
		return DjNoticeUser.dao.findFirst("select * from dj_notice_user u where u.notice_id = '"+id+"' and u.user_id='"+userid+"'");
	}
}
