package org.smartjq.mvc.common.model;

import org.smartjq.mvc.common.model.base.BaseDjNotice;
import org.smartjq.plugin.shiro.ShiroKit;

import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
public class DjNotice extends BaseDjNotice<DjNotice> {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static final DjNotice dao = new DjNotice();
	
	public Page<DjNotice> getPage(int pnum,int psize){
		String userId = ShiroKit.getUserId();
		String sql  = " from dj_notice o where 1=1";

		sql = sql + SysRoleOrg.dao.getRoleOrgSql(userId) ;
		sql = sql + " ORDER BY o.create_time DESC";
		return DjNotice.dao.paginate(pnum, psize, "select * ", sql);
	
	}

	public void findUserNotice(String userId, String para) {
		
	}
}
