package org.smartjq.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDjPartyMember<M extends BaseDjPartyMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setWxId(java.lang.String wxId) {
		set("wx_id", wxId);
	}
	
	public java.lang.String getWxId() {
		return getStr("wx_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}
	
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setNation(java.lang.String nation) {
		set("nation", nation);
	}
	
	public java.lang.String getNation() {
		return getStr("nation");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}
	
	public java.lang.String getAddr() {
		return getStr("addr");
	}

	public void setHomeAddr(java.lang.String homeAddr) {
		set("home_addr", homeAddr);
	}
	
	public java.lang.String getHomeAddr() {
		return getStr("home_addr");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setOther(java.lang.String other) {
		set("other", other);
	}
	
	public java.lang.String getOther() {
		return getStr("other");
	}

	public void setInTime(java.lang.String inTime) {
		set("in_time", inTime);
	}
	
	public java.lang.String getInTime() {
		return getStr("in_time");
	}

	public void setRealTime(java.lang.String realTime) {
		set("real_time", realTime);
	}
	
	public java.lang.String getRealTime() {
		return getStr("real_time");
	}

	public void setIsReal(java.lang.String isReal) {
		set("is_real", isReal);
	}
	
	public java.lang.String getIsReal() {
		return getStr("is_real");
	}

	public void setWxOrgId(java.lang.String wxOrgId) {
		set("wx_org_id", wxOrgId);
	}
	
	public java.lang.String getWxOrgId() {
		return getStr("wx_org_id");
	}

	public void setWxOrgName(java.lang.String wxOrgName) {
		set("wx_org_name", wxOrgName);
	}
	
	public java.lang.String getWxOrgName() {
		return getStr("wx_org_name");
	}

	public void setIsSecretary(java.lang.String isSecretary) {
		set("is_secretary", isSecretary);
	}
	
	public java.lang.String getIsSecretary() {
		return getStr("is_secretary");
	}

	public void setWorkTime(java.lang.String workTime) {
		set("work_time", workTime);
	}
	
	public java.lang.String getWorkTime() {
		return getStr("work_time");
	}

	public void setPosition(java.lang.String position) {
		set("position", position);
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}

	public void setWorkUnit(java.lang.String workUnit) {
		set("work_unit", workUnit);
	}
	
	public java.lang.String getWorkUnit() {
		return getStr("work_unit");
	}

	public void setCompanyType(java.lang.String companyType) {
		set("company_type", companyType);
	}
	
	public java.lang.String getCompanyType() {
		return getStr("company_type");
	}

	public void setCompanyAddr(java.lang.String companyAddr) {
		set("company_addr", companyAddr);
	}
	
	public java.lang.String getCompanyAddr() {
		return getStr("company_addr");
	}

	public void setEduCategory(java.lang.String eduCategory) {
		set("edu_category", eduCategory);
	}
	
	public java.lang.String getEduCategory() {
		return getStr("edu_category");
	}

	public void setEducation(java.lang.String education) {
		set("education", education);
	}
	
	public java.lang.String getEducation() {
		return getStr("education");
	}

	public void setAdmissionTime(java.lang.String admissionTime) {
		set("admission_time", admissionTime);
	}
	
	public java.lang.String getAdmissionTime() {
		return getStr("admission_time");
	}

	public void setDegree(java.lang.String degree) {
		set("degree", degree);
	}
	
	public java.lang.String getDegree() {
		return getStr("degree");
	}

	public void setIsCadre(java.lang.String isCadre) {
		set("is_cadre", isCadre);
	}
	
	public java.lang.String getIsCadre() {
		return getStr("is_cadre");
	}

	public void setOrgId(java.lang.String orgId) {
		set("org_id", orgId);
	}
	
	public java.lang.String getOrgId() {
		return getStr("org_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setSyncTime(java.util.Date syncTime) {
		set("sync_time", syncTime);
	}
	
	public java.util.Date getSyncTime() {
		return get("sync_time");
	}

	public void setDataFrom(java.lang.String dataFrom) {
		set("data_from", dataFrom);
	}
	
	public java.lang.String getDataFrom() {
		return getStr("data_from");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

}
