package org.smartjq.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 * @author CYZ
 */
@SuppressWarnings("serial")
public abstract class BaseEcExamine<M extends BaseEcExamine<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setIid(java.lang.String iid) {
		set("iid", iid);
	}
	
	public java.lang.String getIid() {
		return getStr("iid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setMold(java.lang.Integer mold) {
		set("mold", mold);
	}
	
	public java.lang.Integer getMold() {
		return getInt("mold");
	}

	public void setCycle(java.lang.Integer cycle) {
		set("cycle", cycle);
	}
	
	public java.lang.Integer getCycle() {
		return getInt("cycle");
	}

	public void setFrequency(java.lang.Integer frequency) {
		set("frequency", frequency);
	}
	
	public java.lang.Integer getFrequency() {
		return getInt("frequency");
	}

	public void setFraction(java.lang.Double fraction) {
		set("fraction", fraction);
	}
	
	public java.lang.Double getFraction() {
		return getDouble("fraction");
	}

	public void setScore(java.lang.Double score) {
		set("score", score);
	}
	
	public java.lang.Double getScore() {
		return getDouble("score");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}
	
	public java.lang.String getTarget() {
		return getStr("target");
	}

	public void setIsKey(java.lang.String iskey) {
		set("iskey", iskey);
	}

	public java.lang.String getIsKey() {
		return getStr("iskey");
	}

	public void setOids(java.lang.String oids) {
		set("oids", oids);
	}

	public java.lang.String getOids() {
		return getStr("oids");
	}

	public void setEText(java.lang.String eText) {
		set("e_text", eText);
	}
	
	public java.lang.String getEText() {
		return getStr("e_text");
	}

	public void setEnable(java.lang.String enable) {
		set("enable", enable);
	}

	public java.lang.String getEnable() {
		return getStr("enable");
	}

	public void setSequence(java.lang.Integer sequence) {
		set("sequence", sequence);
	}

	public java.lang.String getSequence() {
		return getStr("sequence");
	}

	public void setAbbr(java.lang.String abbr) {
		set("abbr", abbr);
	}

	public java.lang.String getAbbr() {
		return getStr("abbr");
	}

}
