package org.smartjq.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserCommonFunction<M extends BaseSysUserCommonFunction<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setMenuId(java.lang.String menuId) {
		set("menu_id", menuId);
	}
	
	public java.lang.String getMenuId() {
		return getStr("menu_id");
	}

	public void setIfFixed(java.lang.String ifFixed) {
		set("if_fixed", ifFixed);
	}
	
	public java.lang.String getIfFixed() {
		return getStr("if_fixed");
	}

	public void setIfDel(java.lang.String ifDel) {
		set("if_del", ifDel);
	}
	
	public java.lang.String getIfDel() {
		return getStr("if_del");
	}

	public void setUseTime(java.util.Date useTime) {
		set("use_time", useTime);
	}
	
	public java.util.Date getUseTime() {
		return get("use_time");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

}
