package org.smartjq.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDjSmsLog<M extends BaseDjSmsLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setParams(java.lang.String params) {
		set("params", params);
	}
	
	public java.lang.String getParams() {
		return getStr("params");
	}

	public void setSmsType(java.lang.String smsType) {
		set("sms_type", smsType);
	}
	
	public java.lang.String getSmsType() {
		return getStr("sms_type");
	}

	public void setSendTime(java.lang.String sendTime) {
		set("send_time", sendTime);
	}
	
	public java.lang.String getSendTime() {
		return getStr("send_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

}
