package org.smartjq.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEcExamineMain<M extends BaseEcExamineMain<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setIid(java.lang.String iid) {
		set("iid", iid);
	}
	
	public java.lang.String getIid() {
		return getStr("iid");
	}

	public void setYear(java.lang.String year) {
		set("year", year);
	}
	
	public java.lang.String getYear() {
		return getStr("year");
	}

	public void setOid(java.lang.String oid) {
		set("oid", oid);
	}
	
	public java.lang.String getOid() {
		return getStr("oid");
	}

}
