package org.smartjq.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import org.smartjq.mvc.common.model.EcOrganization;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 * @author CYZ
 */
@SuppressWarnings("serial")
public abstract class BaseEcOrganization<M extends BaseEcOrganization<M>> extends Model<M> implements IBean {

	private List<EcOrganization> children;

	public List<EcOrganization> getChildren() {
		return children;
	}
	public void setChildren(List<EcOrganization> children) {
		this.children = children;
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setFid(java.lang.String fid) {
		set("fid", fid);
	}
	
	public java.lang.String getFid() {
		return getStr("fid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

}
