package org.smartjq.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEcExamineSon<M extends BaseEcExamineSon<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setMid(java.lang.String mid) {
		set("mid", mid);
	}
	
	public java.lang.String getMid() {
		return getStr("mid");
	}

	public void setEid(java.lang.String eid) {
		set("eid", eid);
	}
	
	public java.lang.String getEid() {
		return getStr("eid");
	}

	public void setFraction(java.lang.Double fraction) {
		set("fraction", fraction);
	}
	
	public java.lang.Double getFraction() {
		return getDouble("fraction");
	}

	public void setFrequency(java.lang.Integer frequency) {
		set("frequency", frequency);
	}
	
	public java.lang.Integer getFrequency() {
		return getInt("frequency");
	}

	public void setOid(java.lang.String oid) {
		set("oid", oid);
	}
	
	public java.lang.String getOid() {
		return getStr("oid");
	}

	public void setUidWrite(java.lang.String uidWrite) {
		set("uid_write", uidWrite);
	}
	
	public java.lang.String getUidWrite() {
		return getStr("uid_write");
	}

	public void setDateWrite(java.lang.String dateWrite) {
		set("date_write", dateWrite);
	}
	
	public java.lang.String getDateWrite() {
		return getStr("date_write");
	}

	public void setUidExamine(java.lang.String uidExamine) {
		set("uid_examine", uidExamine);
	}
	
	public java.lang.String getUidExamine() {
		return getStr("uid_examine");
	}

	public void setDateExamine(java.lang.String dateExamine) {
		set("date_examine", dateExamine);
	}
	
	public java.lang.String getDateExamine() {
		return getStr("date_examine");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setIsend(java.lang.String isend) {
		set("isend", isend);
	}
	
	public java.lang.String getIsend() {
		return getStr("isend");
	}

	public void setStatue(java.lang.String statue) {
		set("statue", statue);
	}
	
	public java.lang.String getStatue() {
		return getStr("statue");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return getStr("memo");
	}

	public void setFileName(java.lang.String file_name) {
		set("file_name", file_name);
	}

	public java.lang.String getFileName() {
		return getStr("file_name");
	}

}
