package org.smartjq.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEcExamineAverage<M extends BaseEcExamineAverage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setMid(java.lang.String mid) {
		set("mid", mid);
	}
	
	public java.lang.String getMid() {
		return getStr("mid");
	}

	public void setEid(java.lang.String eid) {
		set("eid", eid);
	}
	
	public java.lang.String getEid() {
		return getStr("eid");
	}

	public void setFraction(java.lang.Double fraction) {
		set("fraction", fraction);
	}
	
	public java.lang.Double getFraction() {
		return getDouble("fraction");
	}

	public void setCumulative(java.lang.Double cumulative) {
		set("cumulative", cumulative);
	}

	public java.lang.Double getCumulative() {
		return getDouble("cumulative");
	}

	public void setFrequency(java.lang.Integer frequency) {
		set("frequency", frequency);
	}
	
	public java.lang.Integer getFrequency() {
		return getInt("frequency");
	}

	public void setDateNew(java.lang.String date_new) {
		set("date_new", date_new);
	}

	public java.lang.String getDateNew() {
		return getStr("date_new");
	}

}
