package org.smartjq.mvc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEcPartyStudent<M extends BaseEcPartyStudent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSchool(java.lang.String school) {
		set("school", school);
	}
	
	public java.lang.String getSchool() {
		return getStr("school");
	}

	public void setZhibu(java.lang.String zhibu) {
		set("zhibu", zhibu);
	}
	
	public java.lang.String getZhibu() {
		return getStr("zhibu");
	}

	public void setGrade(java.lang.String grade) {
		set("grade", grade);
	}
	
	public java.lang.String getGrade() {
		return getStr("grade");
	}

	public void setClasses(java.lang.String classes) {
		set("classes", classes);
	}
	
	public java.lang.String getClasses() {
		return getStr("classes");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setMingzu(java.lang.String mingzu) {
		set("mingzu", mingzu);
	}
	
	public java.lang.String getMingzu() {
		return getStr("mingzu");
	}

	public void setBrith(java.lang.String brith) {
		set("brith", brith);
	}
	
	public java.lang.String getBrith() {
		return getStr("brith");
	}

	public void setGuanji(java.lang.String guanji) {
		set("guanji", guanji);
	}
	
	public java.lang.String getGuanji() {
		return getStr("guanji");
	}

	public void setXueli(java.lang.String xueli) {
		set("xueli", xueli);
	}
	
	public java.lang.String getXueli() {
		return getStr("xueli");
	}

	public void setRudangTime(java.lang.String rudangTime) {
		set("rudang_time", rudangTime);
	}
	
	public java.lang.String getRudangTime() {
		return getStr("rudang_time");
	}

	public void setZhuanzhenTime(java.lang.String zhuanzhenTime) {
		set("zhuanzhen_time", zhuanzhenTime);
	}
	
	public java.lang.String getZhuanzhenTime() {
		return getStr("zhuanzhen_time");
	}

	public void setZsoryb(java.lang.String zsoryb) {
		set("zsoryb", zsoryb);
	}
	
	public java.lang.String getZsoryb() {
		return getStr("zsoryb");
	}

	public void setShenfen(java.lang.String shenfen) {
		set("shenfen", shenfen);
	}
	
	public java.lang.String getShenfen() {
		return getStr("shenfen");
	}

}
